#!/usr/bin/env bash

USER=`whoami`
HOST=`hostname -s`
DOMAIN=`hostname -d`
LOG_LEVEL="${ZOOKEEPER_LOG_LEVEL:-INFO}"
DATA_DIR="${ZOOKEEPER_DATA_DIR:-/var/lib/zookeeper/data}"
DATA_LOG_DIR="${ZOOKEEPER_DATA_LOG_DIR:-/var/lib/zookeeper/data}"
LOG_DIR="${ZOOKEEPER_LOG_DIR:-/var/log/zookeeper}"
CONF_DIR="${ZOOKEEPER_CONF_DIR:-/opt/zookeeper/conf}"
CLIENT_PORT="${ZOOKEEPER_CLIENT_PORT:-2181}"
SERVER_PORT="${ZOOKEEPER_SERVER_PORT:-2888}"
ELECTION_PORT="${ZOOKEEPER_ELECTION_PORT:-3888}"
TICK_TIME="${ZOOKEEPER_TICK_TIME:-2000}"
INIT_LIMIT="${ZOOKEEPER_INIT_LIMIT:-10}"
SYNC_LIMIT="${ZOOKEEPER_SYNC_LIMIT:-5}"
HEAP="${ZOOKEEPER_HEAP:-2G}"
MAX_CLIENT_CNXNS="${ZOOKEEPER_MAX_CLIENT_CNXNS:-60}"
SNAP_RETAIN_COUNT="${ZOOKEEPER_SNAP_RETAIN_COUNT:-3}"
PURGE_INTERVAL="${ZOOKEEPER_PURGE_INTERVAL:-0}"
SERVERS="${ZOOKEEPER_SERVERS:-1}"
PREALLOC_SIZE="${ZOOKEEPER_PREALLOC_SIZE:-1000}"
SNAP_COUNT="${ZOOKEEPER_SNAP_COUNT:-20}"
MIN_SESSION_TIMEOUT="${ZOOKEEPER_MIN_SESSION_TIMEOUT:-10000}"
MAX_SESSION_TIMEOUT="${ZOOKEEPER_MAX_SESSION_TIMEOUT:-40000}"
FOURLW_COMMANDS_WHILELIST="${ZOOKEEPER_FOURLW_COMMANDS_WHILELIST:-stat, ruok, conf, isro}"
ZOOKEEPER_LOG_FILE_LOCATION="${ZOOKEEPER_LOG_FILE_LOCATION:-/var/log/zookeeper/zookeeper.log}"

function print_usage() {
echo "\
Usage: start-zookeeper [OPTIONS]
Starts a ZooKeeper server based on the supplied options.
    --servers           The number of servers in the ensemble. The default
                        value is 1.

    --data_dir          The directory where the ZooKeeper process will store its
                        snapshots. The default is /var/lib/zookeeper/data.

    --data_log_dir      The directory where the ZooKeeper process will store its
                        write ahead log. The default is
                        /var/lib/zookeeper/data/log.

    --conf_dir          The directoyr where the ZooKeeper process will store its
                        configuration. The default is /opt/zookeeper/conf.

    --client_port       The port on which the ZooKeeper process will listen for
                        client requests. The default is 2181.

    --election_port     The port on which the ZooKeeper process will perform
                        leader election. The default is 3888.

    --server_port       The port on which the ZooKeeper process will listen for
                        requests from other servers in the ensemble. The
                        default is 2888.

    --tick_time         The length of a ZooKeeper tick in ms. The default is
                        2000.

    --init_limit        The number of Ticks that an ensemble member is allowed
                        to perform leader election. The default is 10.

    --sync_limit        The maximum session timeout that the ensemble will
                        allows a client to request. The default is 5.

    --heap              The maximum amount of heap to use. The format is the
                        same as that used for the Xmx and Xms parameters to the
                        JVM. e.g. --heap=2G. The default is 2G.

    --max_client_cnxns  The maximum number of client connections that the
                        ZooKeeper process will accept simultaneously. The
                        default is 60.

    --snap_retain_count The maximum number of snapshots the ZooKeeper process
                        will retain if purge_interval is greater than 0. The
                        default is 3.

    --purge_interval    The number of hours the ZooKeeper process will wait
                        between purging its old snapshots. If set to 0 old
                        snapshots will never be purged. The default is 0.

    --max_session_timeout The maximum time in milliseconds for a client session
                        timeout. The default value is 2 * tick time.

    --min_session_timeout The minimum time in milliseconds for a client session
                        timeout. The default value is 20 * tick time.

    --log_level         The log level for the zookeeeper server. Either FATAL,
                        ERROR, WARN, INFO, DEBUG. The default is INFO.
"
}

function create_data_dirs() {
    if [ ! -d $DATA_DIR  ]; then
        mkdir -p $DATA_DIR
        chown -R $USER:$USER $DATA_DIR
    fi

    if [ ! -d $DATA_LOG_DIR  ]; then
        mkdir -p $DATA_LOG_DIR
        chown -R $USER:USER $DATA_LOG_DIR
    fi

    if [ ! -d $LOG_DIR  ]; then
        mkdir -p $LOG_DIR
        chown -R $USER:$USER $LOG_DIR
    fi
    if [ ! -f $ID_FILE ] && [ $SERVERS -gt 1 ]; then
        echo $MY_ID >> $ID_FILE
    fi
}

function print_servers() {
    for (( i=1; i<=$SERVERS; i++ ))
    do
        echo "server.$i=$NAME-$((i-1)).$DOMAIN:$SERVER_PORT:$ELECTION_PORT"
    done
}

function create_config() {
    rm -f $CONFIG_FILE
    echo "#This file was autogenerated DO NOT EDIT" >> $CONFIG_FILE
    echo "clientPort=$CLIENT_PORT" >> $CONFIG_FILE
    echo "dataDir=$DATA_DIR" >> $CONFIG_FILE
    echo "dataLogDir=$DATA_LOG_DIR" >> $CONFIG_FILE
    echo "tickTime=$TICK_TIME" >> $CONFIG_FILE
    echo "initLimit=$INIT_LIMIT" >> $CONFIG_FILE
    echo "syncLimit=$SYNC_LIMIT" >> $CONFIG_FILE
    echo "maxClientCnxns=$MAX_CLIENT_CNXNS" >> $CONFIG_FILE
    echo "minSessionTimeout=$MIN_SESSION_TIMEOUT" >> $CONFIG_FILE
    echo "maxSessionTimeout=$MAX_SESSION_TIMEOUT" >> $CONFIG_FILE
    echo "autopurge.snapRetainCount=$SNAP_RETAIN_COUNT" >> $CONFIG_FILE
    echo "autopurge.purgeInterval=$PURGE_INTERVAL" >> $CONFIG_FILE
    echo "4lw.commands.whitelist=$FOURLW_COMMANDS_WHILELIST" >> $CONFIG_FILE
    echo "preAllocSize=$PREALLOC_SIZE" >> $CONFIG_FILE
    echo "snapCount=$SNAP_COUNT" >> $CONFIG_FILE
     if [ $SERVERS -gt 1 ]; then
        print_servers >> $CONFIG_FILE
    fi
    cat $CONFIG_FILE >&2
}

function create_jvm_props() {
    rm -f $JAVA_ENV_FILE
    echo "ZOO_LOG_DIR=$LOG_DIR" >> $JAVA_ENV_FILE
    echo "JVMFLAGS=\"-Xmx$HEAP -Xms$HEAP\"" >> $JAVA_ENV_FILE
}

function create_log_props() {
    rm -f $LOGGER_PROPS_FILE
    echo "Creating ZooKeeper log4j configuration"
    echo "zookeeper.root.logger=INFO,CONSOLE,ROLLINGFILE" >> $LOGGER_PROPS_FILE
    echo "zookeeper.console.threshold="$LOG_LEVEL >> $LOGGER_PROPS_FILE
    echo "log4j.rootLogger=\${zookeeper.root.logger}" >> $LOGGER_PROPS_FILE
    echo "log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender" >> $LOGGER_PROPS_FILE
    echo "log4j.appender.CONSOLE.Threshold=\${zookeeper.console.threshold}" >> $LOGGER_PROPS_FILE
    echo "log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout" >> $LOGGER_PROPS_FILE
    echo "log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L] - %m%n" >> $LOGGER_PROPS_FILE
    
    echo "log4j.appender.ROLLINGFILE=org.apache.log4j.RollingFileAppender" >> $LOGGER_PROPS_FILE
    echo "log4j.appender.ROLLINGFILE.Threshold="$LOG_LEVEL >> $LOGGER_PROPS_FILE
    echo "log4j.appender.ROLLINGFILE.File="$ZOOKEEPER_LOG_FILE_LOCATION >> $LOGGER_PROPS_FILE
    echo "log4j.appender.ROLLINGFILE.MaxFileSize=10MB" >> $LOGGER_PROPS_FILE
    echo "log4j.appender.ROLLINGFILE.MaxBackupIndex=10" >> $LOGGER_PROPS_FILE
    echo "log4j.appender.ROLLINGFILE.layout=org.apache.log4j.PatternLayout" >> $LOGGER_PROPS_FILE
    echo "log4j.appender.ROLLINGFILE.layout.ConversionPattern=%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L] - %m%n" >> $LOGGER_PROPS_FILE
}

MIN_SESSION_TIMEOUT=${MIN_SESSION_TIMEOUT:- $((TICK_TIME*2))}
MAX_SESSION_TIMEOUT=${MAX_SESSION_TIMEOUT:- $((TICK_TIME*20))}
ID_FILE="$DATA_DIR/myid"
CONFIG_FILE="$CONF_DIR/zoo.cfg"
LOGGER_PROPS_FILE="$CONF_DIR/log4j.properties"
JAVA_ENV_FILE="$CONF_DIR/java.env"
if [[ $HOST =~ (.*)-([0-9]+)$ ]]; then
    NAME=${BASH_REMATCH[1]}
    ORD=${BASH_REMATCH[2]}
else
    echo "Fialed to parse name and ordinal of Pod"
    exit 1
fi

MY_ID=$((ORD+1))

create_config && create_jvm_props && create_log_props && create_data_dirs && exec zkServer.sh start-foreground